name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TITLE_ID: 7633A
  SAMPLE: ""
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  azure-login:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure CLI Get Access Token
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az login --service-principal -u ff61bacc-f588-44ff-b10d-d5041b1309e0 -p i9D8Q~OZZ6ynvfeXJ2.yCVLPeGGtFs6eC2BCQco2 --tenant c8005a3b-1e12-4b8e-a323-917cf9159888
            az account get-access-token --output json > "accessToken.json"
          
      - name: Run Sync Action
        uses: rudyatkinson/custom-action-example@main
        with:
          developer-secret-key: ${{ secrets.DEVELOPER_SECRET_KEY }}
          title-id: ${{ env.TITLE_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID}}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          app-name: ${{ secrets.APP_NAME }}
