# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TITLE_ID: 7633A

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  azure-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login with Credentials
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
          
      - name: Azure CLI Get Access Token
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account get-access-token --output json > ".\accessToken.json"
            echo .\accessToken.json
    
  sync:
    runs-on: ubuntu-latest
    needs: azure-login
    steps:
      # Runs a set of commands using the runners shell
      - name: Run Sync Action
        uses: rudyatkinson/custom-action-example@main
        with:
          developer-secret-key: ${{ secrets.DEVELOPER_SECRET_KEY }}
          title-id: ${{ env.TITLE_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID}}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          app-name: ${{ secrets.APP_NAME }}
          azure-authorization-key: ${{ secrets.AZURE_AUTHORIZATION_KEY }}
